### ISSUE TITLE
editorFocus and editorBlur events do not fire in Chrome or IE

### ISSUE THREAD

**Issue by kpobococ** [cheeaun/mooeditable#10]
Code to reproduce:
    new MooEditable(textarea, {
        'baseCSS': 'html { height: 100%; cursor: text } body.focus { background: red; } ',
        'onEditorFocus': function() {
            this.doc.body.addClass('focus');
        },
        'onEditorBlur': function() {
            this.doc.body.removeClass('focus');
        }
    });

Expected result: iframe body background color change
Actual result: no change in Chrome or IE8

**Comment by cheeaun** [comment]
Fixed in commit 6df322
