### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by orefalo** [cheeaun/mooeditable#12]
This bug only appears on Chrome. Didn't test on IE, but FF and Safari handle it well.
It's a focus issue, which I believe it close to the bug you recently fixed.

On a chrome browser, if you hit the tab key to switch from one <input> to the next, MooEditable doesn't get selected properly. It looks like every button on the toolbar gets selected before it reaches the text area.

Tested with the latest repo from today. Running out of ideas on how to fix this bug.

**Comment by cheeaun** [comment]
That's right, the focus should go to every single button before the textarea. It should be the same for Firefox and Safari as well.
