### ISSUE TITLE
'createlink' should also allow editing of links

### ISSUE THREAD

**Issue by nickolasgregory** [cheeaun/mooeditable#14]
To edit a link you either Remove and Add a link, or view the source to make such a change.
In the 'createlink' command function, this would do it;

```
var node = this.selection.getNode();
if (node.get('href')) prompt.el.getElement('.dialog-input').set('value', node.get('href'));
```

Keep up the good work!

**Comment by cheeaun** [comment]
Thanks. Fixed in 7ad9e62c4aa5456152af9641e9682bb77821f8e6
