### ISSUE TITLE
IE Forecolor unquoted attributes

### ISSUE THREAD

**Issue by LosBanditos** [cheeaun/mooeditable#17]
Hi There,

We found a little bug in the Forecolor function in IE.
If you allready posted some content and you want to edit this content again the HTML code is changed to uppercase elements like FONT and the quotes are gone on the color attribuut.

We use the content output for flash. Without the quoted attributes we get errors.
Ik hope you have a soloution.

Thx
Greetings
Patrick
Los Banditos

**Comment by cheeaun** [comment]
Fixed in c72bc7e4e5e47a89bab00316eeb2c8f213b3f0d0
