### ISSUE TITLE
Safari image moving bug

### ISSUE THREAD

**Issue by ryanmitchell** [cheeaun/mooeditable#18]
Hello

Using Safari 4.0.5 clicking on an image in the mooeditable window and dragging it around would result in the image becoming a broken link icon.

Remove line 380 block:

```
    // make images selectable and draggable in Safari
    if (Browser.Engine.webkit){
        var el = e.target;
        if (el.get('tag') == 'img'){
            this.selection.selectNode(el);
        }
    }
```

And all works as expected...

I'm not sure if I added this originally or you did, but either way it seems redundant now.

Thanks,
Ryan

**Comment by cheeaun** [comment]
I think I added this because when you click on an image in Webkit browsers, there's no indicator that the image is selected, until... you drag them. And I can't seem to reproduce this error on Safari 4.0.5 (Windows). Probably I'll need to try it on Safari Mac.

**Comment by orefalo** [comment]
I just tried on a Mac Safari, opened http://cheeaun.github.com/mooeditable/ added a image via a URL, then clicked the image and moved it around and all worked as expected.

I can confirm that it also works fine in Chrome.

**Comment by ryanmitchell** [comment]
This is very odd. I'll need to have a look on Monday as to whats causing it then. I added a <base url> option to the codebase which might be part of the problem. I'll update this issue once I have tied it down some more.

**Comment by ryanmitchell** [comment]
sorry, it stripped my html. Should have read: I added a (base url="") option to the codebase.
