### ISSUE TITLE
MooEditable.js line 387

### ISSUE THREAD

**Issue by ryanmitchell** [cheeaun/mooeditable#19]
Hello

After this line you need to call this.checkStates() to update Safari's states as the selected node has now changed.

Thanks
Ryan

**Comment by cheeaun** [comment]
Hey Ryan,

Could you give me a use case where checkStates() is needed to be called after the selectNode?

**Comment by ryanmitchell** [comment]
Yeah - what I'm using it for is editing an img properties - like allowing width/height/alt etc to be changed. So in Safari the image button was never showing as selected, as it would always think the paragraph node was selectedNode using checkStates, but when you use the selectNode after clicking the image you should call checkStates so that anything waiting for an image to be selected gets the right information.

**Comment by cheeaun** [comment]
Fixed in 9432b895e2b23da9abad7c819bfe3a58809f6f27
