### ISSUE TITLE
errors with compressed version

### ISSUE THREAD

**Issue by shaunfreeman** [cheeaun/mooeditable#2]
Sorry I accidenty closed this so I have created a new Issue.
There  are some error which stop MooEditable.js from working when compessed:
1. line 39 - baseCSS option should be on one line.
2. line 43 - html option should also be on one line.
3. line 1022 - should have a semi-colon at the end.

so code should look like:
line 39 :-

```
baseCSS: 'html{ height: 100%; cursor: text }\ body{ font-family: sans-serif; border: 0; }',
```

line 43 :-

```
html: '<html>\ <head>\ <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\ <style>{BASECSS} {EXTRACSS}</style>\ {EXTERNALCSS}\ </head>\ <body>{CONTENT}</body>\ </html>'
```

line 1022:-
    input.focus();

see [MooEditable.js](http://github.com/vincentbluff/Uthando-CMS/Source/Common/javascript/Source/MooEditable/MooEditable.js) for edits.

**Comment by cheeaun** [comment]
May I know which compressor are you using?

**Comment by shaunfreeman** [comment]
php version of the Dean Edwards JavaScript's Packer [Packer](http://joliclic.free.fr/php/javascript-packer/en/)
