### ISSUE TITLE
If 'mooeditable-container' is within a hidden element it's width is 0.

### ISSUE THREAD

**Issue by nickolasgregory** [cheeaun/mooeditable#20]
To overcome this I have added another option, 'dimensions',  and changed line 111 to

```
var dimensions = this.options.dimensions || this.textarea.getSize();
```

which works for me.

**Comment by Hdready-graphic** [comment]
Change for (need mootools-more measure) :
var dimensions = this.options.dimensions || this.textarea.measure(function(){return this.getSize();

**Comment by nickolasgregory** [comment]
Is Fixed.
Sorry, cannot find that commit that did it.
