### ISSUE TITLE
The "Remove useless BRs" feature removes all BR following a markup, when the removal should only occur after a block type markup

### ISSUE THREAD

**Issue by olvlvl** [cheeaun/mooeditable#23]
Hello,

I think that the "Remove useless BRs" feature is faulty because it removes all BRs following a markup, when the removal should only occur when the BR is following a block type markups. Consider the following HTML code:

```
<p><strong>Du lundi au vendredi</strong><br />9h - 12h30 / 14h - 19h</p>
```

In this example, the BR element is removed because it follows a STRONG element, but this is unexpected is not desired, and would not happen if "Du lundi au vendredi" was not emphasized. I made a patch, maybe you'll find it useful:

```
if (this.options.paragraphise) source = source.replace(/(div|h1|h2|h3|h4|h5|li|object|ol|p)><br ?\/?>/gi, '$1>');
```

Best regards,

Olivier Laviale

**Comment by cheeaun** [comment]
Thanks! Fixed in 74e1c276aa938673a257e2c0613915142a5ffa8e
