### ISSUE TITLE
Firefox doesn't replace selection the first time selection.insertContent is called

### ISSUE THREAD

**Issue by tru10000** [cheeaun/mooeditable#27]
Can you reproduce this bug also? I'm testing on Firefox 3.6 on Snow Leopard. I figured out a hack to fix the problem. 

Change line 288:
        this.selection = new MooEditable.Selection(this.win, this);
Change the initialize function of MooEditable.Selection to: 
    initialize: function(win, editor){
        this.win = win;
        this.editor = editor;
    },
Then add this before the insertHTML line in the nonIE section of the insertContent function: 
            if (Browser.firefox) {
                this.win.document.execCommand('insertHTML', false, content);
                this.editor.execute('undo');
            }

**Comment by cheeaun** [comment]
Fixed in 2d31ec65445e55b40792370d3db8536087b1b428 with a slightly different solution
