### ISSUE TITLE
Link to documentation doesn't work

### ISSUE THREAD

**Issue by IsabelPalomar** [cheeaun/mooeditable#62]
Hi! I just click the link specified in the gh-page, but it load a blank page
![blank_docs](https://f.cloud.github.com/assets/930751/1081740/82190698-157b-11e3-91dd-0fce951b4f9b.png).

**Comment by cheeaun** [comment]
Fixed in 2c81c76335cbf28569a7527cc8a0b60abaca6fcd and d847babde10f7defbb1275a8ac07f004dcc5cdae

**Comment by IsabelPalomar** [comment]
:+1:
