### ISSUE TITLE
Add Etherpad to list of editors?

### ISSUE THREAD

**Issue by JohnMcLear** [cheeaun/mooeditable#66]
https://github.com/cheeaun/mooeditable/wiki/Javascript-WYSIWYG-editors

Etherpad uses it's own Editor..

**Comment by cheeaun** [comment]
Hmm perhaps I'm confused:

> @krues8dr ah nice, not sure if it's really a wysiwyg editor tho' if say, exclude the live editing part.
> - https://twitter.com/cheeaun/status/636409015690391552

Just wondering if engineers can use it without the live-editing server part(?).

**Comment by JohnMcLear** [comment]
Yep engineers can with a little hacking

**Comment by cheeaun** [comment]
:+1: added

**Comment by krusynth** [comment]
:+1:
