### ISSUE TITLE
preformated text in <pre> lose formating

### ISSUE THREAD

**Issue by xrado** [cheeaun/mooeditable#7]
after toggling the view preformated text looses formating,
new lines become html line breaks

**Comment by xrado** [comment]
i was experimenting with this already, somehow if iframe and textarea stay visible the whole time while toggling formatting will not get corrupted, strange...

**Comment by cheeaun** [comment]
This is probably because of the cleanup regex... :(

**Comment by xrado** [comment]
no, I had cleanup turned off

**Comment by cheeaun** [comment]
I think I found the problem. Firefox is adding those &lt;br ..&gt;s automatically. Even when you type something in the &lt;pre&gt; in wysiwyg mode, Firefox will create &lt;br ..&gt;s as well. So, I guess we'll need regex to clean those up...

**Comment by xrado** [comment]
good idea! :) just did it and tested it and works fine ..cool
http://github.com/xrado/mooeditable/commit/5b10e28e5266f77a378674dc585c1c34c2cef7ed
